ユーザー認証を実装。Deviseを導入
yoshikouki/books_app pull request #5
Opened 2020-07-22 07:58 UTC by yoshikouki

# 実装したこと

- ユーザー認証を導入
- Deviseをインストール・初期設定
- Userモデルを作成
- ユーザー機能周りのI18nに対応

2020-07-23 08:08 UTC, june29 commented on app/views/layouts/_header.html.haml
> +    -# ログアウト時
「ログイン時」の対義語として「ログアウト時」というフレーズを使っているのだと想像しました。しかし、ここで表現したいことは「未ログイン時」「非ログイン時」といった方がより実態に近いかと思います。なぜなら、たとえば初回訪問者は「ログアウトしたことはない」はずなので、ログアウト時にマッチするかは怪しいですよね。

さらに言えば、ぼくは、

```
  - if user_signed_in?
    A
  - else
    B
```

これだけ見れば「ログイン中と非ログイン中の分岐だな」と想像できたので、日本語のコメント自体が不要では？と思いました。

2020-07-23 08:10 UTC, june29 commented on config/locales/views/ja.yml
> +      # page_title: 'New book'
コメントアウトしてまで残そうと思ったのはどうしてですか？ :smiley:

2020-07-23 12:10 UTC, yoshikouki commented on app/views/layouts/_header.html.haml
> +    -# ログアウト時
確かに「ログアウト時」というのはこのコード内の条件を網羅できていない表現でした！
また明らかに見れば分かる処理なのでコメントが冗長になってしまっている点、納得しました😂

修正いたします！

2020-07-23 12:12 UTC, yoshikouki commented on config/locales/views/ja.yml
> +      # page_title: 'New book'
お恥ずかしながら削除忘れです・・・
こういう確認漏れが少し多いようですので、今後プルリク作成後にはFiles Changedを確認するなど注意して振り返るようにいたします

2020-07-30 12:29 UTC, komagata commented
> add/ Devise をインストール・初期設定 …

こういうコミットが残っているようです。

2020-07-30 12:29 UTC, komagata requested changes
> add/ Devise をインストール・初期設定 …

こういうコミットが残っているようです。

2020-08-03 08:28 UTC, komagata requested changes

2020-08-03 08:28 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.page(params[:page]).per(10)
Magic Numberになっているのでkaminariの機能を使って設定するか、定数にしたいですね。

2020-08-03 08:28 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
こちらのよくあるミス3を確認してみてください〜

[devise を使ってユーザー認証を実装する](https://bootcamp.fjord.jp/practices/40)

2021-11-04 11:50 UTC, closed without merging