ActiveStorageを利用してユーザーのプロフィール画像機能を実装
yoshikouki/books_app pull request #8
Opened 2020-07-29 07:29 UTC by yoshikouki

# 実装項目

- ActiveStorage の初期設定
- User モデルにActiveStorage利用の設定
- プロフィール画像の編集・表示機能

2020-07-29 07:42 UTC, june29 commented on app/models/user.rb
> +  def self.find_for_github_oauth(auth, _signed_in_resource = nil)
第 2 引数の _signed_in_resource って、どういうことをやろうとしていたんですか？

2020-07-29 07:44 UTC, june29 commented on app/models/user.rb
> +  def self.create_unique_string
Rails の文脈だと create は ActiveRecord の create を想像して「データベースのレコードに追記しそう」とぼくは思うので、こういうケースではぼくは `generate_` はじまりのメソッド名を採用することが多いです。参考まで〜 :wave:

2020-07-29 07:45 UTC, june29 commented on app/models/user.rb
> +  def self.create_unique_string
わざわざメソッド化せずに SecureRandom.uuid をそのまま使うのでもいいんじゃない？と思ったり。

2020-07-29 08:59 UTC, yoshikouki commented on app/models/user.rb
> +  def self.find_for_github_oauth(auth, _signed_in_resource = nil)
お恥ずかしながらコピペで記述されているものを残してしまっていた次第です
昨日のエラーに阻まれてたときに特に考えずに残してしまっていました・・・

コメントもらって良くないコードを上げてしまったなと気付けました

2020-07-29 09:03 UTC, yoshikouki commented on app/models/user.rb
> +  def self.create_unique_string
使っているフレームワークで単語の文脈が変わってくるということですね
確かにここ一箇所でしか使用していませんのでメソッド化する必要はなかったです

2020-07-29 13:11 UTC, june29 commented on app/models/user.rb
> +  def self.find_for_github_oauth(auth, _signed_in_resource = nil)
おー、そういうことでしたら、これはよくないタイプのコピペでしたね :joy:
気付きにつながったのならコメントした甲斐がありました :v:

2020-07-29 17:43 UTC, komagata commented
コミットの整理お願いいたします〜

前のプラクティスを元にしているのであればrebaseでそれらを反映させればこのブランチでの変更点（コミット）は少しになると思います。

この辺りのgit操作は実務でバンバン出てくるのでこの研修でいろいろ弄って試しちゃってください〜

2020-07-30 12:26 UTC, komagata requested changes

2020-07-30 12:26 UTC, komagata commented on .generators
> +<?xml version="1.0" encoding="UTF-8"?>
これってなんのファイルでしょう〜

2020-07-30 12:26 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.page(params[:page]).per(10)
Magic NumberになっているのでKaminariの機能を使って設定するか、定数を使いたいですね。

2020-07-30 12:26 UTC, komagata commented on app/controllers/books_controller.rb
> +    @book.save ? redirect_to(@book, notice: t('.success')) : render(:new)
if - elseを使いたいです〜（他のPRで指摘した部分と同じ理由になります）

2020-07-30 12:26 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
こちら不要です。下記のよくあるミス3を参照していただければ〜

[devise を使ってユーザー認証を実装する](https://bootcamp.fjord.jp/practices/40)

2021-11-04 11:50 UTC, closed without merging